sonar.projectKey=jame-jafari
sonar.projectName=Jame Jafari
sonar.sources=src,frontend/src
sonar.exclusions=**/bin/**,**/obj/**,**/node_modules/**,**/dist/**,**/Migrations/**
sonar.sourceEncoding=UTF-8
