/** Central API path helpers — keeps views free of scattered route strings. */
export const ApiPaths = {
  accounts: '/accounts',
  account: (id) => `/accounts/${id}`,
  costTypes: '/cost-types',
  costType: (id) => `/cost-types/${id}`,
  generalTypes: '/general-types',
  generalType: (id) => `/general-types/${id}`,
  incomeTransactions: '/income-transactions',
  incomeTransaction: (id) => `/income-transactions/${id}`,
  incomeTransactionAttachment: (id, attachmentId) => `/income-transactions/${id}/attachments/${attachmentId}`,
  costTransactions: '/cost-transactions',
  costTransaction: (id) => `/cost-transactions/${id}`,
  costTransactionAttachment: (id, attachmentId) => `/cost-transactions/${id}/attachments/${attachmentId}`,
  persons: '/persons',
  person: (id) => `/persons/${id}`,
  users: '/users',
  user: (id) => `/users/${id}`,
  food: '/food',
  foodItem: (id) => `/food/${id}`,
  foodRecommendations: '/food/recommendations',
  reports: {
    accountBalances: '/reports/account-balances',
    costTypes: '/reports/cost-types',
    summary: '/reports/summary',
    personIncome: '/reports/person-income',
    foodCosts: '/reports/food-costs',
    deathAnniversaries: '/reports/death-anniversaries'
  },
  lookups: {
    accounts: '/lookups/accounts',
    costTypes: '/lookups/cost-types',
    generalTypes: '/lookups/general-types',
    persons: '/lookups/persons',
    messageChannels: '/lookups/message-channels',
    personGroups: '/lookups/person-groups'
  },
  baleMessages: '/bale-messages',
  baleMessage: (id, scope = 'remote') => `/bale-messages/${id}?scope=${scope}`,
  baleConfig: '/bale-messages/config',
  baleSyncContacts: '/bale-messages/sync-contacts',
  messageChannels: '/message-channels',
  messageChannel: (id) => `/message-channels/${id}`,
  personGroups: '/person-groups',
  personGroup: (id) => `/person-groups/${id}`,
  incomeTransactionSendReceipt: (id) => `/income-transactions/${id}/send-receipt`
}
